# S3 Storage setup
endpoint = "https://pasted.nbg1.your-objectstorage.com"
access = "DHXDO3GT5PAOMVO6H2J4"
secret = "7IZnmc4h0j2Dg6atEcUnBWmkrvNFRbuuzkVOWsCt"

# Database setup
database_uri = "mysql+pymysql://pasted:resc2009@localhost:3306/pasted"

# Basic config
max_file_size_regular = 128
max_file_size_premium = 512