#!/usr/bin/env python3

import logging

import waitress

logger = logging.getLogger("waitress").setLevel(logging.INFO)

if __name__ == "__main__":
    from app import app

    waitress.serve(app, host="127.0.0.1", port=5000)
